name:                text-utils
version:             0.1.0.0
synopsis:            Various text utilities
description:         Please see README.md
homepage:            https://github.com/agrafix/text-utils#readme
license:             MIT
author:              Alexander Thiemann
maintainer:          mail@athiemann.net
copyright:           2016 Alexander Thiemann <mail@athiemann.net>
category:            Web

dependencies:
  - base >= 4.7 && < 5
  - text

library:
  source-dirs: src
  exposed-modules:
    - Data.Text.KGrams

tests:
  spec:
    cpp-options: -DTest
    main: Test.hs
    source-dirs:
      - test
      - src
    dependencies:
      - HTF
